### ISSUE TITLE
allow to select a node programmatically

### ISSUE THREAD

**Issue by Trass3r** [tintinweb/vscode-interactive-graphviz#10]
And make the currently selected node stand out more visually.

**Comment by tintinweb** [comment]
can you elaborate?

**Comment by Trass3r** [comment]
Well an API to change the selected node.

**Comment by bigbug** [comment]
Hey @Trass3r,
can you check in [https://github.com/bigbug/vscode-interactive-graphviz/tree/newsearch](https://github.com/bigbug/vscode-interactive-graphviz/tree/newsearch) whether this fits your needs?

The existing command is hereby extended to the following:
```
let args = {
    document: <vscode.document>,
    content: <string: dotSrc>,
    callback: <function (webpanel){}>,
    allowMultiplePanels: <bool: false|[true]>,
    title: <string: RenderWindowTitle>,
    search: <string|SearchObject|null>
}

vscode.commands.executeCommand("graphviz-interactive-preview.preview.beside", args)
```

On providing just a string, the current search functionality is executed. If you provide a SearchObject, then the highlight mode is activated (there is currently no GUI for this). The SearchObject has the following Spec:
```
let searchObject = {
    text: <string>, // required
    options?: {
        type?: "exact"|"included"|"regex", // used search function. default: "exact"
        direction?: "bidirectional"|"upstream"|"downstream"|"single",
        nodeName?: <bool: true>, // should search in node names
        nodeLabel?: <bool: true>, // should search in node labels
        edgeLabel?: <bool: true>, // should search in edge labels
    }
}
```

Greetings,
bigbug
