### ISSUE TITLE
svg export does not escape angle brackets in node labels

### ISSUE THREAD

**Issue by Trass3r** [tintinweb/vscode-interactive-graphviz#11]
```
<g id="node16" class="node" data-name="load<Foo>(\nconst string &amp; key, bool bla)" data-comment="..the same again..">
-------------------------------------------^
```

**Comment by tintinweb** [comment]
Thanks for the report @Trass3r.

There are probably more cases where HTML-entities are not encoded according to the SVG spec. Did you find this by validating the output or did this cause any major problems?

**Comment by Trass3r** [comment]
The svgs can't be displayed cause of that, in browsers at least.

**Comment by bigbug** [comment]
@Trass3r: Can you provide an example digraph for which it fails?

**Comment by bigbug** [comment]
Can reproduce with
```dot
digraph test {
	"load<Foo>(const string & key, bool bla)";
}
```

Error Message:

> This page contains the following errors:
error on line 7 at column 68: Unescaped '<' not allowed in attributes values
Below is a rendering of the page up to the first error.
