### ISSUE TITLE
Formatter deletes comments and all whitespace on save

### ISSUE THREAD

**Issue by protosam** [tintinweb/vscode-interactive-graphviz#110]
The problem is that if your graphviz file looks like this and you save it:
```dot
strict digraph {
  /* This block comment is important or something. */

  // I want to remember this later....
  // layout = "dot";
  node [
    fillcolor = "#ffffff",
  ];

  // general note related to nothing important

  // cool info here about this connection
  "hello" -> "graph";
}
```

Gets transformed into this:
```dot
strict digraph {
  node [
    fillcolor = "#ffffff",
  ];
  // cool info here about this connection
  "hello" -> "graph";
}
```

The assertions being made by the formatter are really wild. 

Temporary solution for users is to just disable it.
- Open the command palette (`CTRL+Shift+P` or `Command+Shift+P`)
- Search for and open `Preferences: Open Settings (JSON)`
- Add the following in the settings and save (take note that there is a comma at the end of this snippet)
```json
    "[dot]": {
        "editor.formatOnSave": false
    },
```

**Comment by bigbug** [comment]
Problem confirmed. Seems to be caused by the underlying libraries [https://github.com/ts-graphviz/parser](https://github.com/ts-graphviz/parser) and [https://github.com/ts-graphviz/ts-graphviz](https://github.com/ts-graphviz/ts-graphviz). I will try to investigate this further and report the problems there.

**Comment by bigbug** [comment]
We used the parser from ts-graphviz/parser and the toDot method from ts-graphviz/ts-graphviz. Inbetween these two the comments get lost.

The following code uses parse and stringify from ts-graphviz/parser. This fixes the comments getting lost. However, the indentation seems to be off.
```typescript
const d = AST.parse(document.getText());
const dot = AST.stringify(d);
```

**Comment by bigbug** [comment]
Output of formatter has been adapted. Given the input from the start of the issue, the formatter now generates the following code by default (an option called `graphviz-interactive-preview.format.condenseAttributes` has been introduced, which has an impact on how attributes are shown):
```dot
strict digraph {
    /**
     * This block comment is important or something.
     */
    
    // I want to remember this later....
    // layout = "dot";
    
    node [fillcolor = "#ffffff";];
    
    // general note related to nothing important
    
    // cool info here about this connection
    "hello" -> "graph";
}
```

**Comment by protosam** [comment]
Nice update! Found bug with the changes. Going to continue to conversation in the PR.
