### ISSUE TITLE
prevented typing in *.dot files with invalid syntax, slowed creation of new files

### ISSUE THREAD

**Issue by absurdist** [tintinweb/vscode-interactive-graphviz#112]
Issue Type: <b>Bug</b>

opened a dot file template (not valid dot syntax)
had not chosen to preview file
could not type in file, 

Creating new files in the file browser pane took minutes

Extension version: 0.3.0
VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.05GB free)|
|Process Argv|--crash-reporter-id bc8553e4-e90c-473c-a6d0-ed2788027676|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bigbug** [comment]
Is this reproducible?
Can you provide the template file?

**Comment by absurdist** [comment]
Hi Bigbug, I'll try reproduce the error in the morning and if I can, I'll send the template seemed to cause the error.

**Comment by bigbug** [comment]
Closed due to inactivity
