### ISSUE TITLE
Add configuration for graphviz options like font style

### ISSUE THREAD

**Issue by ketozhang** [tintinweb/vscode-interactive-graphviz#118]
Graphviz has multiple CLI options. One that would be useful is to globally change the font:

```sh
$ dot -Nfontname="Calibri" graph.dot
```

I'd love to see those configurable in VSCode settings

**Comment by bigbug** [comment]
Currently this is not possible, since hpccWasm does not support these options. We could style it with CSS, however, this would look different after exporting. So I think this will not be implemented until the feature is supported by hpccWasm.

**Comment by bigbug** [comment]
Will not be done with the current setup. Changes in hpccWasm necessary.
