### ISSUE TITLE
Multiple paths with different label

### ISSUE THREAD

**Issue by qingshannet** [tintinweb/vscode-interactive-graphviz#12]
When there are two or more same path with different label, it only highlights one of the path. Could this be enhanced?

Thanks

**Comment by bigbug** [comment]
Verified with
`digraph {
a -> b
a -> b
}`

<img width="298" alt="Screenshot 2022-01-11 at 18 36 52" src="https://user-images.githubusercontent.com/27259/148993188-0e49ab4b-84da-4934-812b-22ccfe001cda.png">

**Comment by tintinweb** [comment]
fixed in #30
