### ISSUE TITLE
Support for adjusting to VS Code theme

### ISSUE THREAD

**Issue by mforkel** [tintinweb/vscode-interactive-graphviz#120]
I use Graphviz Interactive Preview to display dot graphs created by `quilt graph`. These graphs do not contain any color or font information. That results in black nodes and edges on a white background, which does not match well with most VS Code color themes.

Currently, I adapt the graph source with [gvpr](https://linux.die.net/man/1/gvpr) and a program file like
```
BEG_G {
    bgcolor="#1e1e1e"       // editor.background
}
N {
    color="#d4d4d4",        // editor.foreground
    fontcolor="#d4d4d4",    // editor.foreground
    fontname="Consolas",
    fontsize="14pt"
}
E {
    color="#d4d4d4",        // editor.foreground
    fontcolor="#d4d4d4",    // editor.foreground
    fontname="Consolas",
    fontsize="14pt"
}
```
That is not a real solution. The actual color values are [not available to an extension](https://github.com/Microsoft/vscode/issues/32813) or to the user, so they can't be provided programmatically or in the configuration. But color and font information [is available through CSS variables in webviews](https://code.visualstudio.com/api/extension-guides/webview#theming-webview-content). 

Would it be possible to add an option for the display of graphs to change the default values for graph display to those of the current VS Code theme?

**Comment by bigbug** [comment]
That's something I already tried in [](https://github.com/tintinweb/vscode-interactive-graphviz/issues/72). However, it needs some more polishing, which I canˋt do at the moment.

**Comment by mforkel** [comment]
Just discovered your own issue #72. Sorry I missed it. I guess that's what you're referring to in you reply ("tried in ")?

**Comment by bigbug** [comment]
Exactly. Unfortunately it currently looks like this if the nodes have the attribute "filled":
<img width="878" alt="Screenshot 2022-08-06 at 20 54 03" src="https://user-images.githubusercontent.com/27259/183262397-a06e3e28-4523-4a4f-ba5e-7163ecbef0dd.png">
