### ISSUE TITLE
preview shape of nodes

### ISSUE THREAD

**Issue by dzmitry-lahoda** [tintinweb/vscode-interactive-graphviz#137]
in editor
```
a [ shape = box3d]
```

literally shows
```
a [ shape = <HERE IS BOX> box3d]
```
(like color is shown)

or shown visual when you type only (selecting shape from list) or when mouse over. 

so instead of rendering I can know what will be ahead

it is hard to find good shape from list as some shapes have weird names

**Comment by dzmitry-lahoda** [comment]
will donate 5 DOT for on this

**Comment by bigbug** [comment]
Current working state:
<img width="1055" alt="Screenshot 2022-10-25 at 22 25 07" src="https://user-images.githubusercontent.com/27259/197874676-2f0d502e-622d-4cd5-87da-f0deea744d8c.png">
