### ISSUE TITLE
Empty render since vscode 1.56.0

### ISSUE THREAD

**Issue by tintinweb** [tintinweb/vscode-interactive-graphviz#15]
tracking https://github.com/microsoft/vscode/issues/123822

**Comment by jfthuong** [comment]
I noticed this issue 2 days ago and I was just checking on your repo if there was a related issue. Awesome ;)

Hope it can be resolved soon because I love your extension!

**Comment by tintinweb** [comment]
v0.0.11 is out, addressing the issue. let me know if it is still not rendering and Ill take a look. @jfthuong 

cheers
