### ISSUE TITLE
How to add a file extensions in VSCode?

### ISSUE THREAD

**Issue by Acry** [tintinweb/vscode-interactive-graphviz#152]
graphiz brings [examples](https://gitlab.com/graphviz/graphviz/-/tree/main/graphs/). My package brings the examples in `/usr/share/graphviz/graphs`, those have the extension `.gv`.  I can't find a proper settings to extend the extension list.

![image](https://user-images.githubusercontent.com/3709175/215470017-ac76cf46-b48a-4b67-aede-6cec9affc9ef.png)

Can anyone help me?

Cheers,
Acry

**Comment by bigbug** [comment]
Hi Acry, our extension currently supports *.dot and *.gv out of the box. Other files have to be opened with VS Code and then the language can be selected at the lower right corner in VS Code.
If you want to make a permanent setting, you can use VS Code's setting `files.associations`:
<img width="688" alt="Screenshot 2023-02-04 at 17 57 55" src="https://user-images.githubusercontent.com/27259/216779794-36100b4b-9963-4767-a8f3-9a1cdfeb6d30.png">
