### ISSUE TITLE
Add filtering

### ISSUE THREAD

**Issue by ookami-kb** [tintinweb/vscode-interactive-graphviz#154]
Hey, thanks for the extension, it really helps a lot.

It would be great if we could do filtering by nodes/clusters. I'm using this extension to analyze dependencies graphs, and there are 2 problems:

1. It becomes really laggy on mid-sized graphs (350 nodes / 1150 edges).
2. I don't always need to view the whole graph, usually I can work with a subset. 
 
Both problems could be solved by filtering: either showing a module (i.e. cluster) in isolation (to check the internal dependencies) or adding upstream/downstream dependencies.

Similar to what we can now do by highlighting, but removing unaffected elements from rendering.

**Comment by bigbug** [comment]
Hi, we already created a feature which might help you in your use case.
However it's not yet published and will come with us releasing #104.
<img width="669" alt="Screenshot 2023-03-04 at 19 20 48" src="https://user-images.githubusercontent.com/27259/222922468-ffb4e0f3-a940-4461-972d-caa139cf31d6.png">
