### ISSUE TITLE
in the current release of vscode this plugin is broken

### ISSUE THREAD

**Issue by RobVerduijn** [tintinweb/vscode-interactive-graphviz#168]
A simple dot file

digraph switches {
  sw1 -> sw2;
  sw1 -- sw3;
}

gives the error
null function or function signature mismatch

vscode version
Version: 1.87.2
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:14:59.643Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 6.7.9-200.fc39.x86_64

graphviz interactive preview v0.3.5

**Comment by adamsmd** [comment]
I am seeing the same issue, so I don't know why this is marked as closed. @RobVerduijn did you find a fix?

**Comment by RobVerduijn** [comment]
Hello, it's not broken, works as designed
I was using a non directional edge in a directional graph 

a--b is non directional, if you wish to use this in a directional graph you need to add a direction none behind it

so in a directional graph:
```graphviz
digraph switches {
sw1 -> sw2;
sw1 -> sw3[dir=none];
}
```
or in a graph

```graphviz
graph switches {
sw1 -- sw2;
sw1 -- sw3[dir=forward];
}
```
at best there could be a more friendly error
