### ISSUE TITLE
how to enable preview?

### ISSUE THREAD

**Issue by SHuang-Broad** [tintinweb/vscode-interactive-graphviz#17]
Hi, 

I just installed this but what should I do to enable the preview?
I tried the `cmd + v` and `cmd + k + v` and `cmd + shift + v`, none seem to work and it seems to render the dot file as plain text. 

Am I mis-configuring the IDE (I'm new to VS Code)?

Thanks!
Steve

<img width="1536" alt="Screen Shot 2021-06-29 at 11 09 53 AM" src="https://user-images.githubusercontent.com/16310888/123822795-97667600-d8ca-11eb-827a-b4a7a9b0da91.png">

**Comment by tintinweb** [comment]
hi @SHuang-Broad,

`cmd + shift + p` ->  `graphviz preview beside` is your friend. You can set your own hotkeys for commands in vscode. 

![wiz](https://user-images.githubusercontent.com/2865694/123979106-b7786100-d9c0-11eb-8779-f646c67dddb4.gif)
