### ISSUE TITLE
Focusing a node does not work consistently

### ISSUE THREAD

**Issue by Phrogz** [tintinweb/vscode-interactive-graphviz#21]
Viewer sometimes gets into a state where clicking on a node does not focus the incoming/outgoing. Have not yet figured out how to reproduce.

**Comment by tintinweb** [comment]
Hey @Phrogz,

I think I've observed that too and found out that if you hit the label on the node it might not focus. I'll see if there's a way we can fix that. Also happy to merge a PR if you happen to fix it :) 

cheers and happy holidays.

**Comment by bigbug** [comment]
@tintinweb: Can you reproduce it?

**Comment by tintinweb** [comment]
should be fixed with #34 (thanks @bigbug)
