### ISSUE TITLE
Feature request: copy to clipboard

### ISSUE THREAD

**Issue by Phrogz** [tintinweb/vscode-interactive-graphviz#23]
Instead of screenshotting and manually selecting the graph, it would make it easier to perform quick one-off shares (e.g. pasting in Slack) if there was a button or option to copy the current image to the clipboard.

Even better if there's a setting that allows the image placed on the clipboard to be a larger resolution than what's shown on screen.

**Comment by tintinweb** [comment]
Hey @Phrogz,

there is a button to save as `.dot` or `.svg` if that helps?

![image](https://user-images.githubusercontent.com/2865694/147289329-4add73d1-2759-4242-86ab-3dae1a18ef2c.png)

**Comment by tintinweb** [comment]
I recommend to export the SVG and work on that. generating a raster image from a sub-portion of a vector image is not that easy.

cheers
