### ISSUE TITLE
Allow highlighting only upstream or downstream dependencies in a DAG

### ISSUE THREAD

**Issue by justinchuby** [tintinweb/vscode-interactive-graphviz#27]
I love the feature where I can select a node and see all the connected nodes. It would be great to have a toggle for highlighting only upstream or downstream dependencies in a DAG. This will help working with big graphs when one wants to understand which nodes contribute to a node.

**Comment by justinchuby** [comment]
Love the change. Could you publish the new version to the marketplace?

**Comment by tintinweb** [comment]
published 👉 https://github.com/tintinweb/vscode-interactive-graphviz/releases/tag/v0.0.13
