### ISSUE TITLE
Clickable nodes

### ISSUE THREAD

**Issue by bigbug** [tintinweb/vscode-interactive-graphviz#33]
On nodes only the actual rendered lines are clickable. The rest is not clickable. In the following example only the ellipsis line and the label are clickable. The white space within the ellipsis is not clickable - but I think it should be.

`digraph { a -> b a-> c }`

The marked red area is currently not clickable (same applies to node b and c):
<img width="558" alt="Screenshot 2022-01-15 at 14 50 42" src="https://user-images.githubusercontent.com/27259/149624129-8b53faac-dd7f-4ebd-ac49-ec99244b5efc.png">

Maybe related to #21?

**Comment by tintinweb** [comment]
excellent! the old behavior was very annoying, thanks for the PR!

fixed with #34
