### ISSUE TITLE
Progress indicator

### ISSUE THREAD

**Issue by bigbug** [tintinweb/vscode-interactive-graphviz#36]
On running large DOT files (e.g. example from [https://gist.githubusercontent.com/williame/4087256/raw/4911df0fe4c4186eb482bd4a2162bd55cc698d67/gistfile1.txt](https://gist.githubusercontent.com/williame/4087256/raw/4911df0fe4c4186eb482bd4a2162bd55cc698d67/gistfile1.txt) ) it seems, that the there is nothing going on. The screen stays empty and there is no indication, that the Renderer is still running. This should be fixed using either an (indefinite) progress bar or some other kind of indicator.

**Comment by tintinweb** [comment]
I like proposal #37 adding a progress indicator and warning that it might be necessary to adjust the render settings 👍

**Comment by bigbug** [comment]
Also linked to #42

**Comment by tintinweb** [comment]
merged https://github.com/tintinweb/vscode-interactive-graphviz/commit/785e9fd8eded22203667dd138868233106760a1b (https://github.com/tintinweb/vscode-interactive-graphviz/blob/master/src/features/interactiveWebview.ts#L68-L76)
