### ISSUE TITLE
[Bug] No preview auto-refresh while typing

### ISSUE THREAD

**Issue by pidgeon777** [tintinweb/vscode-interactive-graphviz#4]
The preview window doesn't automatically refresh when I start typing in the code editor. Even if I save the file at the end.

My setup is:

- Windows 10 Professional x64
- Visual Studio Code 1.42.0

**Comment by tintinweb** [comment]
this can happen if dot language support is not installed with vscode. I've changed the behavior of this extension to also listen for change events if the filesname endswith `.dot`.
