### ISSUE TITLE
graph render can be outdated when changing the graph

### ISSUE THREAD

**Issue by tintinweb** [tintinweb/vscode-interactive-graphviz#5]
when changing the graph the preview is updated automatically. however, this is only done verye 5 seconds to avoid breaking the tracing. see #3

**Comment by izzues** [comment]
First of all, thanks for the great work!

Not sure if this would completely solve the issue, but wouldn't it be better to first [debounce](https://davidwalsh.name/javascript-debounce-function) rendering?

If you're not familiar with the idea:
- Create a counter and set it to zero;
- Whenever the user modifies something, set the counter to some fixed positive value (let's say two seconds);
- When the counter goes to zero (i.e. two seconds of idleness), the render function is called.

Of course, this could still be combined with the throttling function.

Maybe the time to debounce could be calculated from the cost of rendering or something like that.

**Comment by tintinweb** [comment]
thanks @michkot for addressing this issue!
