### ISSUE TITLE
Use a bright color for highlighting search results

### ISSUE THREAD

**Issue by justinchuby** [tintinweb/vscode-interactive-graphviz#59]
The current highlight color for node search results is a light blue color. It is hard to notice when the node itself is colored. It would be nice to adapt the color to make the highlight more obvious, or use a brighter color by default (yellow?)

**Comment by bigbug** [comment]
The current search is basically just a browser based search. So VS Code or the underlying Electron/Chromium engine handle the search. We are currently preparing our 0.1.0 release which integrates our own search system and highlights nodes just like a click on a node does.

**Comment by bigbug** [comment]
Highlighting should be better with our current release 0.1.0.
