### ISSUE TITLE
Allow fuzzy match in search

### ISSUE THREAD

**Issue by justinchuby** [tintinweb/vscode-interactive-graphviz#60]
Searching only matches full strings at the moment. For working with very big graphs, it helps to allow fuzzy match or prefix match in the search feature.

**Comment by bigbug** [comment]
Our new search system (as also described in #59) will introduce the support of regex search. Would that be sufficient for you?

**Comment by justinchuby** [comment]
Regex search would be very nice, and I think it will be sufficient for my use case. Thanks!
