### ISSUE TITLE
Support For All GraphViz Renderers

### ISSUE THREAD

**Issue by nickspurry** [tintinweb/vscode-interactive-graphviz#69]
In version 0.1.2, graphs appear to be rendered using the dot GraphViz renderer equivalent, with no option to switch to the other renderers supported by d3-graphviz, such as neato, fdp etc. Since all of the standard GraphViz renderers are supported by both d3-graphviz and hpcc-js-wasm, it seems like using any of the renderers should be relatively easy.

Suggest that support for other render types be added to the vscode extension if possible.

**Comment by bigbug** [comment]
How would you like to see this integrated? Shall this be an option in the GUI to select from? Or are there special markers available in the DOT file to react on that?

**Comment by nickspurry** [comment]
I think it would need to be a drop down item in the GUI, I'm not aware of any specific DOT file instructions to select a renderer. There are some DOT file instructions that are only applicable to specific renderers (i.e. if a different renderer is used they have no effect), perhaps they could be used to make an intelligent default choice about which renderer to use, but this might be unnecessary complexity. Using DOT by default and allowing the user to select something else if they want would probably also work quite well.

**Comment by bigbug** [comment]
Has been implemented in pull request #85.
