### ISSUE TITLE
Clicking on the background brings it to foreground, covering the nodes

### ISSUE THREAD

**Issue by justinchuby** [tintinweb/vscode-interactive-graphviz#70]
Clicking on the background brings it to the front. This makes it impossible to click back on the nodes that are covered.

Steps to reproduce

1. Select the background of a subgraph
2. Press <kbd>esc</kbd>
3. The background is now on top of the nodes

![Kapture 2022-02-27 at 21 13 50](https://user-images.githubusercontent.com/11205048/155927911-7f4b39e1-3741-4c95-abbf-48e8a8869e8a.gif)

**Comment by bigbug** [comment]
Hmmm, probably this is some problem with [jquery.graphviz.svg.js](https://github.com/tintinweb/vscode-interactive-graphviz/blob/master/content/graphvizSvg/jquery.graphviz.svg.js). Either `bringToFront()` or `highlight()` might be the origin (they are both called from [content/highlighting.js](https://github.com/tintinweb/vscode-interactive-graphviz/blob/master/content/highlighting.js).
I currently don't have that much time to look into it (will get better in April). Help would be appreciated!
