### ISSUE TITLE
Format source code

### ISSUE THREAD

**Issue by bigbug** [tintinweb/vscode-interactive-graphviz#78]
We should provide a possibility to format the source code so that the dot file always gets formatted the exact same way.
[https://code.visualstudio.com/api/language-extensions/programmatic-language-features#format-source-code-in-an-editor](https://code.visualstudio.com/api/language-extensions/programmatic-language-features#format-source-code-in-an-editor)

**Comment by tintinweb** [comment]
merged with #97
