### ISSUE TITLE
How do I get the preview to render in dark mode?

### ISSUE THREAD

**Issue by axefrog** [tintinweb/vscode-interactive-graphviz#9]
In the screenshots, you show the graph rendering with a dark theme. I use a dark theme, and just created a simple dot file. In the preview though, the graph is shown as black outlines on a white background. What do I need to do to show the preview in dark mode?

**Comment by notanaverageman** [comment]
You can get the theme from [this comment](https://github.com/tintinweb/vscode-interactive-graphviz/issues/2#issuecomment-586525472) on #2.

Specifically add following lines to top-most graph:

```dot
graph [ ratio = "auto", page = "100", compound =true, bgcolor = "#2e3e56" ];
node [ style = "filled", fillcolor = "#edad56", color = "#edad56", penwidth =3 ];
edge [ color = "#fcfcfc", penwidth =2, fontname = "helvetica Neue Ultra Light" ];
```

Add the following line to each subgraph:

```dot
graph [ color = "#445773", fontcolor = "#f0f0f0", style = "rounded", bgcolor = "#445773" ];
```

**Comment by tintinweb** [comment]
thx @notanaverageman
